#!/bin/bash

set -u
set -e

BASE_DIR=$HOME/.config/yadm

# Ensure `sudo`
echo 'Checking for `sudo` access (may request your password)...'
sudo true

# Install needed apt packages
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install ansible

# Run ansible playbook
cd $BASE_DIR/playbook/
ansible-galaxy install -r requirements.yml
echo 'Running ansible playbook - enter `sudo` password:'
ansible-playbook main.yml --ask-become-pass
