#!/bin/bash

set -u
set -e

# Ensure `sudo`
echo 'Checking for `sudo` access (may request your password)...'
sudo true

# Initialize variables
BASE_DIR=$HOME/.config/yadm
REQUIREMENTS_DIR=$BASE_DIR/requirements

# Install python and pip requirements
sudo apt install python3 python3-pip
python3 -m pip install -r $REQUIREMENTS_DIR/pip.txt

# Run the install script
echo "\nRunning install script..."
python3 $BASE_DIR/install.py
